### ISSUE TITLE
Deprecated dependence

### ISSUE THREAD

**Issue by Oui-Dev** [cmseguin/rollup-plugin-react-scoped-css#47]
I just install the lib and it work well but i got this warning :
"npm WARN deprecated consolidate@0.15.1: Please upgrade to consolidate v1.0.0+ as it has been modernized with several long-awaited fixes implemented. Maintenance is supported by Forward Email at https://forwardemail.net ; follow/watch https://github.com/ladjs/consolidate for updates and release changelog"

**Comment by Oui-Dev** [comment]
Thanks for the update, but the warning still present after updated to 0.8.4 :/

**Comment by cmseguin** [comment]
Oh sorry about that, I think this might be coming from the vue dependency
and I updated it to the latest version. I suspect this will get updated
soon... But we are also working on removing that dependency in favor of
something else! There will be an alpha release of 1.0.0 soon! Hopefully
that'll fix all the issues! :)

**Comment by cmseguin** [comment]
@Oui-Dev I released an alpha version (I thought npm would not publish this as a full release but it did -_-) but you could try this release if you want. Also if you want to test it and give me feedback on if it works well for you that would be greatly appreciated since we are removing the "vue engine" and that was the package throwing the error I believe.

**Comment by Oui-Dev** [comment]
Thanks for the quick update, I'll try to test this within the week :)

**Comment by Oui-Dev** [comment]
I try to install this morning, and the warning disapear but when i try to `npm run dev` i got this error

`
✘ [ERROR] Failed to resolve entry for package "rollup-plugin-react-scoped-css". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]

    node_modules/esbuild/lib/main.js:1373:27:
      1373 │         let result = await callback({
           ╵                            ^

    at packageEntryFailure (file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at resolveByViteResolver (file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66217:32)
    at file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66258:40
    at requestCallbacks.on-resolve (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1373:28)
    at handleRequest (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66243:27)
    at handlePlugins (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:786:5)
    at /Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:2177:15
    at new Promise (<anonymous>)
    at Object.build (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:2176:25)
    at build (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:2025:51)
    at bundleConfigFile (file:///Users/xxxxxx/Documents/xxxxxxxx/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:66194:26)

  The plugin "externalize-deps" was triggered by this import

    vite.config.js:4:37:
      4 │ import { reactScopedCssPlugin } from 'rollup-plugin-react-scoped-css';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /Users/xxxxxx/Documents/xxxxxxxx/vite.config.js
error when starting dev server:
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1373:27: ERROR: [plugin: externalize-deps] Failed to resolve entry for package "rollup-plugin-react-scoped-css". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/xxxxxx/Documents/xxxxxxxx/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
`

i install it through my package.json like this

`
    "dependencies": {
        ...
        "rollup-plugin-react-scoped-css": "cmseguin/rollup-plugin-react-scoped-css#releases/1.0.0-alpha"
    }
`

**Comment by cmseguin** [comment]
Oh just do this: 
```
"dependencies": {
        ...
        "rollup-plugin-react-scoped-css": "1.0.0-alpha.6"
    }
```

or simpler 

`yarn add -D rollup-plugin-react-scoped-css@alpha` or ``npm i -D rollup-plugin-react-scoped-css@alpha``

**Comment by Oui-Dev** [comment]
My bad ! Now it work like i want, no issue at this point :)

**Comment by Oui-Dev** [comment]
I get my first issue with the package in alpha (im already in alpha 6) @cmseguin .

When using a map like this
`            {data.map((elt, index) => (
                <Fragment key={index}>
                    <div>
                        ...
                    </div>
                    <div>
                        ...
                    </div>
                </Fragment>
            ))}`
            
I get this warning `Warning: Invalid prop `data-v-961215c6` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.`, and if I remove import of my scoped scss file the warning disappear.
